# Basic Site Settings
title                    : "周佳楠 / Jia'nan Zhou - 学术主页"
title_separator          : "-"
name                     : &name "Jia'nan Zhou"
description              : &description "四川大学软件学院2023级本科生，专注于人工智能、计算机视觉与AI安全研究"
url                      : "https://ranger1213123.github.io"  # ← 请替换为你自己的 GitHub Pages 地址
baseurl                  : "" 
repository               : "ranger1213123/ranger1213123.github.io"  # ← 改为你 fork 的仓库名

# Site Author
author:
  avatar           : "profile.png"  
  name             : "Jia'nan Zhou"
  pronouns         : "he/him"
  bio              : "四川大学软件学院2023级本科生 | 人工智能与计算机视觉研究者"
  location         : "成都，四川，中国"
  employer         : "四川大学软件学院"
  uri              : "https://www.scu.edu.cn"  # 可填学校/实验室链接
  email            : "ranger13love@163.com"  # 建议创建一个 academic 用邮箱

  # Academic profiles (可选填)
  googlescholar    : # 你可以放你自己的 Scholar 链接
  orcid            : # http://orcid.org/你的 ORCID ID
  researchgate     : 
  pubmed           : 
  semantic         : 
  arxiv            : 

  # Repositories
  github           : "ranger1213123"  # 改为你自己的 GitHub 用户名
  kaggle           : "ranger1213123"
  stackoverflow    : 

  # Social media（任选填写）
  linkedin         : 
  zhihu            : 
  twitter          : 
  weibo            : 
