# Basic Site Settings
title                    : "Jia'nan Zhou / 周佳楠的学术主页"
title_separator          : "-"
name                     : &name "Jia'nan Zhou"
description              : &description "Undergraduate in Software Engineering at Sichuan University, passionate about computer vision and AI research."
url                      : "https://ranger1213123.github.io"  # ← 请替换为你自己的 GitHub Pages 地址
baseurl                  : "" 
repository               : "ranger1213123/ranger1213123.github.io"  # ← 改为你 fork 的仓库名

# Site Author
author:
  avatar           : "profile.png"  
  name             : "Jia'nan Zhou"
  pronouns         : "he/him"
  bio              : "Grade 2 at Sichuan University | Passionate about AI, Computer Vision, and Research"
  location         : "Chengdu, Sichuan, China"
  employer         : "Sichuan University"
  uri              :  # 可填学校/实验室链接
  email            : "ranger13love@163.com"  # 建议创建一个 academic 用邮箱

  # Academic profiles (可选填)
  googlescholar    : # 你可以放你自己的 Scholar 链接
  orcid            : # http://orcid.org/你的 ORCID ID
  researchgate     : 
  pubmed           : 
  semantic         : 
  arxiv            : 

  # Repositories
  github           : "ranger1213123"  # 改为你自己的 GitHub 用户名
  kaggle           : "ranger1213123"
  stackoverflow    : 

  # Social media（任选填写）
  linkedin         : 
  zhihu            : 
  twitter          : 
  weibo            : 
